name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
          - name: Echo Hola
            run: echo "Hola"

    dev-deploy:
        needs: docker
        runs-on: ubuntu-latest
        environment:
            name: development
        steps:
          - uses: actions/checkout@v4
          - uses: azure/setup-kubectl@v3
            with:
                version: v1.26.0
          - uses: azure/k8s-set-context@v3
            with:
                method: kubeconfig
                kubeconfig: '${{ secrets.KUBECONFIG }}'
          - run: kubectl version